package com.exam;
// Generated Jun 28, 2019 3:18:34 AM by Hibernate Tools 4.3.1



/**
 * Candidate generated by hbm2java
 */
public class Candidate  implements java.io.Serializable {


     private Integer cid;
     private String candidatename;
     private String location;
     private String party;
     private String image;

    public Candidate() {
    }

    public Candidate(String candidatename, String location, String party, String image) {
       this.candidatename = candidatename;
       this.location = location;
       this.party = party;
       this.image = image;
    }
   
    public Integer getCid() {
        return this.cid;
    }
    
    public void setCid(Integer cid) {
        this.cid = cid;
    }
    public String getCandidatename() {
        return this.candidatename;
    }
    
    public void setCandidatename(String candidatename) {
        this.candidatename = candidatename;
    }
    public String getLocation() {
        return this.location;
    }
    
    public void setLocation(String location) {
        this.location = location;
    }
    public String getParty() {
        return this.party;
    }
    
    public void setParty(String party) {
        this.party = party;
    }
    public String getImage() {
        return this.image;
    }
    
    public void setImage(String image) {
        this.image = image;
    }




}


