package com.exam;
// Generated Jun 28, 2019 3:18:34 AM by Hibernate Tools 4.3.1



/**
 * Tempvoter generated by hbm2java
 */
public class Tempvoter  implements java.io.Serializable {


     private Integer tid;
     private String nid;
     private byte[] voted;

    public Tempvoter() {
    }

    public Tempvoter(String nid, byte[] voted) {
       this.nid = nid;
       this.voted = voted;
    }
   
    public Integer getTid() {
        return this.tid;
    }
    
    public void setTid(Integer tid) {
        this.tid = tid;
    }
    public String getNid() {
        return this.nid;
    }
    
    public void setNid(String nid) {
        this.nid = nid;
    }
    public byte[] getVoted() {
        return this.voted;
    }
    
    public void setVoted(byte[] voted) {
        this.voted = voted;
    }




}


