package com.exam;
// Generated Jun 28, 2019 3:18:34 AM by Hibernate Tools 4.3.1



/**
 * Voter generated by hbm2java
 */
public class Voter  implements java.io.Serializable {


     private Integer vid;
     private String fullname;
     private String fathername;
     private String mothername;
     private String address;
     private String dob;
     private Integer nid;
     private String gender;
     private String image;
     private String location;

    public Voter() {
    }

    public Voter(String fullname, String fathername, String mothername, String address, String dob, Integer nid, String gender, String image, String location) {
       this.fullname = fullname;
       this.fathername = fathername;
       this.mothername = mothername;
       this.address = address;
       this.dob = dob;
       this.nid = nid;
       this.gender = gender;
       this.image = image;
       this.location = location;
    }
   
    public Integer getVid() {
        return this.vid;
    }
    
    public void setVid(Integer vid) {
        this.vid = vid;
    }
    public String getFullname() {
        return this.fullname;
    }
    
    public void setFullname(String fullname) {
        this.fullname = fullname;
    }
    public String getFathername() {
        return this.fathername;
    }
    
    public void setFathername(String fathername) {
        this.fathername = fathername;
    }
    public String getMothername() {
        return this.mothername;
    }
    
    public void setMothername(String mothername) {
        this.mothername = mothername;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public String getDob() {
        return this.dob;
    }
    
    public void setDob(String dob) {
        this.dob = dob;
    }
    public Integer getNid() {
        return this.nid;
    }
    
    public void setNid(Integer nid) {
        this.nid = nid;
    }
    public String getGender() {
        return this.gender;
    }
    
    public void setGender(String gender) {
        this.gender = gender;
    }
    public String getImage() {
        return this.image;
    }
    
    public void setImage(String image) {
        this.image = image;
    }
    public String getLocation() {
        return this.location;
    }
    
    public void setLocation(String location) {
        this.location = location;
    }




}


